services:
  blazor:
    build: source_code/Barbershop
    command: dotnet run
    ports:
      - "80:8080"
    environment:
      DATABASE_STRING: Host=host.docker.internal;Port=1488;Database=pharma;Username=postgres;Password=Roflanxlebalo
    depends_on:
      postgres:
        condition: service_healthy
        

  postgres:
    image: postgres
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Barbershop
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 1488:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 1234:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret

volumes:
  pgdata: